# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.16.0
_src_path: https://github.com/mbercx/python-copier
coverage: codecov
doc_deploy: rtd
docs: mkdocs
package_name: qe-tools
type_check: loose
