default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        name: Lint with Ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        name: Format with Ruff
        types_or: [ python, pyi ]

  - repo: local
    hooks:
      - id: mypy
        name: Type-check with mypy
        entry: mypy
        language: system
        types: [ python ]
        require_serial: true
        files: ^src/

  - repo: local
    hooks:
      - id: check-commit-msg
        name: Check commit message format
        entry: python dev/check_commit_msg.py
        language: system
        stages: [commit-msg]

