site_name: qe-tools

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - getting_started.md
  - developer.md
  - Design: 
    - design/scope.md
    - design/quicknotes.md
    - design/public_api.md
    - design/outputs_desired_usage.md
    - design/inputs_desired_usage.md
