name: ci

on: [push, pull_request]

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v2

        -   name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.9'
                cache: 'pip'
                cache-dependency-path: pyproject.toml

        -   name: Install Python package and dependencies
            run: pip install -e .[dev]

        -   name: Run pre-commit
            run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    tests:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.9']

        steps:
        -   uses: actions/checkout@v2

        -   name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
                cache-dependency-path: pyproject.toml

        -   name: Install Python package and dependencies
            run: pip install -e .[dev]

        -   name: Run pytest
            run: pytest -sv --cov=qe_tools --cov-config=.coveragerc tests

        -   name: Run codecov
            run: codecov
